# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Finding
tagline:          'for life'
description:      'write something valueable'
url:              http://changzhiwin.github.io

author:
  name:           'changzhiwin'
  url:            http://changzhiwin.github.io

baseurl:          http://changzhiwin.github.io/poole/

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
